trainer: mpdr 
logger: base 
model:
  arch: mpdr_joint
  ae:
    arch: vaebm
    ckpt_path: models/vaebm/vaebm_pretrained/cifar10/checkpoint.pt
    spherical: False 
  mpdr:
    temperature: 1
    gamma_vx: 1
    gamma_vz: 1
    sigma_schedule: constant 
    sigma_start: 0.1
    sigma_end: 0.1
    num_timesteps: 50
    sampling_x: langevin 
    sampling_s: gaussian 
    mcmc_n_step_x: 5
    mcmc_stepsize_x: 100
    mcmc_noise_x: 0.001
    mcmc_bound_x: [0, 1]
    mcmc_custom_stepsize: True
    mcmc_n_step_omi: 10
    mcmc_stepsize_omi: 0.05
    mcmc_noise_omi: 0.02
    mcmc_normalize_omi: True
    proj_mode: constant
    proj_noise_start: 0.05
    proj_noise_end: 0.05
    # proj_const: 0.0001
    proj_const: 0
      # proj_dist: geodesic
    proj_dist: sum 
    l2_norm_reg_netx: null 
    use_net_z: False 
    use_recon_error: False
    grad_clip_off: null
    update_ae: null
    energy_method: null
    recovery_gaussian_blur:
      kernel_size: 5
    apply_proj_grad: 0 
  net_x:
      arch: conv3fc 
      out_activation: linear
      activation: leakyrelu 
      nh: 8
      use_spectral_norm: True 
      learn_out_scale: True
  net_s: null
  net_z: null
      # learn_out_scale: True
  x_dim: 3
  z_dim: 16
data:
    indist_train:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 32
        n_workers: 8
        split: training
        augmentations:
          hflip:
            p: 0.5
    indist_val:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation 
    ood_svhn:
        dataset: SVHN_OOD 
        channel: 3
        path: datasets
        batch_size: 128
        split: validation
        n_workers: 2
    ood_constant:
        dataset: Constant_OOD 
        size: 32
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation
    ood_celeba32:
        dataset: CelebA_OOD 
        size: 32
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation
    ood_cifar100:
        dataset: CIFAR100_OOD 
        path: datasets
        batch_size: 128
        n_workers: 2
        split: evaluation 
training:
    load_ae: null
    ae_epoch: 0 
    nae_epoch: 50
    print_interval: 500
    print_interval_nae: 100
    val_interval: 5000
    val_interval_nae: 100 
    save_interval: 5000
    ae_lr: 1.0e-4
    nae_lr: 1.0e-4
    sample_val_interval: null
    mode: 'off' 
