trainer: mpdr 
logger: base 
model:
  arch: mpdr_joint
  ae:
    encoder: 
      arch: IGEBMEncoderV2
      use_spectral_norm: True 
      keepdim: True
      out_activation: linear 
      avg_pool_dim: 4
    decoder:
      arch: sngan_generator_gn 
      hidden_dim: 128
      num_groups: 2
      out_activation: sigmoid
      spatial_dim: 4
    spherical: True
    encoding_noise: 0.01
      # l2_norm_reg_enc: 0.00001 
    tau: 1
    neg_coef: 1.
  mpdr:
    temperature: 1
    gamma_vx: 1
    gamma_vz: 1
    sigma_schedule: constant 
    sigma_start: 0.1
    sigma_end: 0.1
    num_timesteps: 50
    sampling_x: langevin 
    sampling_s: gaussian 
    mcmc_n_step_x: 5
    mcmc_stepsize_x: 100
    mcmc_noise_x: 0.001
    mcmc_bound_x: [0, 1]
    mcmc_custom_stepsize: True
    mcmc_n_step_omi: 10
    mcmc_stepsize_omi: 10
    mcmc_noise_omi: 0.02
    proj_mode: constant
    proj_noise_start: 0.05
    proj_noise_end: 0.05
    # proj_const: 0.0001
    proj_const: 0
    proj_dist: geodesic
    l2_norm_reg_netx: null 
    use_net_z: False 
    grad_clip_off: null
    update_ae: null
    energy_method: null
    recovery_gaussian_blur:
      kernel_size: 5
    apply_proj_grad: 0 
  net_x:
    arch: IGEBMEncoderV2
    use_spectral_norm: True 
    keepdim: True
    learn_out_scale: True
  net_s:
    arch: fcnet_temb
    activation: relu
    spec_norm: True 
    hidden_dim: 128 
    t_emb_dim: 256 
  net_z:
    arch: convmlp 
    activation: leakyrelu 
    out_activation: linear
    use_spectral_norm: True 
    spatial_dim: 4
    l_hidden: [256, 256] 
      # learn_out_scale: True
  x_dim: 3
  z_dim: 16
data:
    indist_train:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 64
        n_workers: 8
        split: training
        augmentations:
          hflip:
            p: 0.5
    indist_val:
        dataset: CIFAR10_OOD 
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation 
    ood_svhn:
        dataset: SVHN_OOD 
        channel: 3
        path: datasets
        batch_size: 128
        split: validation
        n_workers: 2
    ood_constant:
        dataset: Constant_OOD 
        size: 32
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation
    ood_celeba32:
        dataset: CelebA_OOD 
        size: 32
        path: datasets
        batch_size: 128
        n_workers: 2
        split: validation
    ood_cifar100:
        dataset: CIFAR100_OOD 
        path: datasets
        batch_size: 128
        n_workers: 2
        split: evaluation 
training:
    load_ae: results_mpdr/research/cifar10_joint/v4_z128_spatial_omi_aug/z256_rcrop_cjitter_perceptual_l1/model_last.pkl
    ae_epoch: 240
    nae_epoch: 50
    print_interval: 500
    print_interval_nae: 100
    val_interval: 5000
    val_interval_nae: 100 
    save_interval: 5000
    ae_lr: 1.0e-4
    nae_lr: 1.0e-4
    sample_val_interval: null
    mode: 'off' 
