trainer: ood
logger: base
model:
  arch: ae_mpdr_v5
  decoder:
    arch: fc
    l_hidden:
        - 128
        - 128
        - 128
        - 128
    activation: leakyrelu
    out_activation: linear
    batch_norm: False 
    out_batch_norm: False
  encoder:
    arch: fc
    l_hidden:
        - 128
        - 128
        - 128
        - 128
    activation: relu
    out_activation: linear 
    batch_norm: False 
    out_batch_norm: False 
  x_dim: 640
  z_dim: 128
  l2_norm_reg_enc: 0.00001
  spherical: True
training:
    n_epoch: 101
    save_interval: 100
    val_interval: 1000
    print_interval: 100
    optimizer:
        name:  'adam'
        lr: 1.0e-4
    save_interval_epoch: 50
