trainer: ood
logger: base
model:
    arch: igebm 
    net: 
        arch: IGEBMEncoderV2
        use_spectral_norm: True
        learn_out_scale: True
    x_dim: 1
    noise_std: 0.005
    step_size: 10
    sample_step: 60
    langevin_clip_grad: null
    buffer_size: 10000
      # clip_x: Null
data:
    indist_train:
        dataset: MNISTLeaveOut
        path: datasets
        out_class: 9
        shuffle: True
        holdout: False
        split: training
        batch_size: 128
        n_workers: 2 
    indist_val:
        dataset: MNISTLeaveOut
        path: datasets
        out_class: 9
        shuffle: True
        holdout: False
        split: validation 
        batch_size: 128
        n_workers: 2 
    ood1:
        dataset: Constant_OOD 
        size: 28
        channel: 1
        path: datasets
        split: validation
        batch_size: 128
        n_workers: 2 
    ood2:
        dataset: MNISTLeaveOut
        path: datasets
        out_class: 9
        holdout: True
        split: validation
        batch_size: 128
        n_workers: 2 
training:
    n_epoch: 100
    save_interval: 2000
    val_interval: 500
    print_interval: 100
    optimizer:
        name:  'adam'
        lr: 1.0e-4
    save_interval_epoch: 1
