trainer: mpdr 
logger: base 
model:
  arch: mpdr_single
  ae:
    decoder:
      arch: deconv2
      nh: 8
      out_activation: sigmoid
    encoder:
      arch: conv2fc
      nh: 8
      nh_mlp: 1024
      out_activation: linear 
    spherical: True
      # encoding_noise: 0.01 
    l2_norm_reg_enc: 0.0001 
  net_x:
    arch: ae 
    decoder:
      arch: deconv2
      nh: 8
      out_activation: sigmoid
    encoder:
      arch: conv2fc
      nh: 8
      nh_mlp: 1024
      out_activation: linear 
    spherical: True
    l2_norm_reg_enc: 0.0001 
    z_dim: 32
    x_dim: 1
    learn_out_scale: True

  mpdr:
    temperature: 1
    temperature_omi: 1
    gamma_vx: null
    gamma_neg_recon: 1.
    sampling_x: langevin 
    mcmc_n_step_x: 5
    mcmc_stepsize_x: 10
    mcmc_noise_x: 0.005
    mcmc_bound_x: [0, 1]
    mcmc_custom_stepsize: True
    mcmc_n_step_omi: 5
    mcmc_stepsize_omi: 0.1
    mcmc_noise_omi: 0.02
    mcmc_normalize_omi: True 
    proj_mode: uniform 
    proj_noise_start: 0.05
    proj_noise_end: 0.3
    proj_const_omi: 0.0001
    proj_const: 0.0001
    l2_norm_reg_netx: null 
    use_recon_error: False
    grad_clip_off: null
    energy_method: null 
    custom_netx_reg: True
  net_s: null
  net_z: null
  x_dim: 1
  z_dim: 32
data:
  indist_train:
    batch_size: 128
    dataset: MNISTLeaveOut
    n_workers: 8
    out_class: 9
    path: datasets
    shuffle: true
    holdout: False
    split: training
  indist_val:
    batch_size: 128
    dataset: MNISTLeaveOut
    n_workers: 2
    out_class: 9
    holdout: False
    path: datasets
    split: validation
  ood_mnist9:
    batch_size: 128
    dataset: MNISTLeaveOut
    n_workers: 2
    out_class: 9
    holdout: True
    path: datasets
    split: validation
  ood_constant:
    batch_size: 128
    channel: 1
    dataset: Constant_OOD
    n_workers: 2
    path: datasets
    size: 28
    split: validation
  ood_halfmnist:
    batch_size: 128
    dataset: HalfMNIST
    split: validation
    n_workers: 2
    path: datasets
training:
  # load_ae:  results_mpdr/mnist_ho_mpdr/vs1/v5_z32_ae/omi5_omis0.1_newae_noenc_l2enc5/model_last.pkl
    load_ae: null
    ae_epoch: 30 
    netx_epoch: 0
    nae_epoch: 60
    print_interval: 500
    print_interval_netx: 500
    print_interval_nae: 100
    val_interval: 5000
    val_interval_nae: 100 
    sample_val_interval: null  # no sampling
    save_interval: 5000
    ae_lr: 0.0001
    netx_lr: 0.0001
    nae_lr: 1.0e-5
    mode: 'off' 
    transfer_ae: True 
