trainer: mpdr 
logger: base 
model:
  arch: mpdr_joint
  ae:
    encoder: 
      arch: fc 
      use_spectral_norm: True 
      out_activation: linear 
      activation: leakyrelu 
      l_hidden: [1024]
    decoder:
      arch: fc 
      use_spectral_norm: True 
      out_activation: linear 
      activation: leakyrelu 
      l_hidden: [1024]
    spherical: True
    encoding_noise: 0.01
      # l2_norm_reg_enc: 0.00001 
  mpdr:
    temperature: 1
    gamma_vx: 1
    gamma_vz: 1
    sigma_schedule: constant 
    sigma_start: 0.1
    sigma_end: 0.1
    num_timesteps: 50
    sampling_x: langevin 
    sampling_s: gaussian 
    mcmc_n_step_x: 5
    mcmc_stepsize_x: 1
    mcmc_noise_x: 0.05
    mcmc_bound_x: [0, 1]
    mcmc_custom_stepsize: False 
    mcmc_n_step_omi: null
    mcmc_stepsize_omi: 1
    mcmc_noise_omi: 0.02
    proj_mode: uniform 
    proj_noise_start: 0.05
    proj_noise_end: 0.2
    # proj_const: 0.0001
    proj_const: 0.1
    proj_dist: geodesic
    l2_norm_reg_netx: null 
    use_net_z: False 
    grad_clip_off: null
    update_ae: null
    energy_method: null
    use_recon_error: True
  net_x:
    arch: fc 
    use_spectral_norm: True 
    l_hidden: [256, 256]
    out_activation: linear
    activation: leakyrelu
    learn_out_scale: True
  net_s:
    arch: fcnet_temb
    activation: relu
    spec_norm: True 
    hidden_dim: 128 
    t_emb_dim: 256 
  net_z: null
  x_dim: 768
  z_dim: 16 
data:
    indist_train:
        dataset: ExtractedFeature
        path: datasets
        filename: null
        override: False
        extract_hflip: True 
        extract_device: cuda:0
        extract_center_crop: False
        split: training
        batch_size: 64
        n_workers: 0
        bound: [-8, 8]
        model_name: vit_base_patch16_224
        shuffle: True
        dataset_dict:
          dataset: CIFAR100_OOD 
          path: datasets
          batch_size: 64
          n_workers: 0
          augmentations: 'None'
    indist_val:
        dataset: ExtractedFeature
        path: datasets
        filename: null
        override: False
        extract_hflip: True 
        extract_device: cuda:0
        extract_center_crop: False
        split: validation 
        batch_size: 64
        n_workers: 4
        bound: [-8, 8]
        model_name: vit_base_patch16_224
        dataset_dict:
          dataset: CIFAR100_OOD 
          path: datasets
          batch_size: 64
          n_workers: 0
          augmentations: 'None'
    ood_svhn:
        dataset: ExtractedFeature
        path: datasets
        filename: null
        override: False
        extract_hflip: False 
        extract_device: cuda:0
        extract_center_crop: False
        split: validation 
        batch_size: 64
        n_workers: 4
        bound: [-8, 8]
        model_name: vit_base_patch16_224
        dataset_dict:
          dataset: SVHN_OOD 
          path: datasets
          batch_size: 64
          n_workers: 0
          augmentations: 'None'
    ood_cifar10:
        dataset: ExtractedFeature
        path: datasets
        filename: null
        override: False
        extract_hflip: False 
        extract_device: cuda:0
        extract_center_crop: False
        split: validation 
        batch_size: 64
        n_workers: 4
        bound: [-8, 8]
        model_name: vit_base_patch16_224
        dataset_dict:
          dataset: CIFAR10_OOD 
          path: datasets
          batch_size: 64
          n_workers: 0
          augmentations: 'None'
training:
    load_ae: null
    ae_epoch: 30
    nae_epoch: 20
    print_interval: 500
    print_interval_nae: 100
    val_interval: 500
    val_interval_nae: 100 
    save_interval: 500
    ae_lr: 1.0e-4
    nae_lr: 1.0e-4
    sample_val_interval: null
    mode: 'off' 
    load_best_ae: True
